network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: false
      dhcp6: false
      addresses:
      - 192.168.122.150/24
      routes:
      - to: default
        via: 192.168.122.1
      nameservers:
       addresses: [208.67.222.222,192.168.122.1]